# 导出 WEB_DIRECTORY 以便 ComfyUI 自动加载 web 目录下的 JS 扩展
WEB_DIRECTORY = "./web"

# 该插件仅包含 UI 扩展，不需要后端节点
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]